version: "3.0"

services:
  proxy:
    image: haproxy:1.7
    networks:
      main:
        aliases:
          - proxy
    ports:
      - "11110:11110"
    volumes:
      - "./conf:/usr/local/etc/haproxy:ro"

  uniq1:
    image: golang:1.7
    networks:
      main:
        aliases:
          - uniq1
    volumes:
      - ".:/usr/local/go/src/github.com/bculberson/uniq:rw"
    command: bash -c "go run main.go -s --haddr uniq1:11111 --raddr uniq1:11112"
    working_dir: /usr/local/go/src/github.com/bculberson/uniq

  uniq2:
    image: golang:1.7
    networks:
      main:
        aliases:
          - uniq2
    volumes:
      - ".:/usr/local/go/src/github.com/bculberson/uniq:rw"
    command: bash -c "sleep 3 && go run main.go --join proxy:11110 --haddr uniq2:11113 --raddr uniq2:11114"
    working_dir: /usr/local/go/src/github.com/bculberson/uniq

  uniq3:
    image: golang:1.7
    networks:
      main:
        aliases:
          - uniq3
    volumes:
      - ".:/usr/local/go/src/github.com/bculberson/uniq:rw"
    command: bash -c "sleep 3 && go run main.go --join proxy:11110 --haddr uniq3:11115 --raddr uniq3:11116"
    working_dir: /usr/local/go/src/github.com/bculberson/uniq

networks:
  main: