version: "2"

services:
  proxy:
    image: haproxy:1.7
    networks:
      - my-net
    ports:
      - "11110:11110"
    volumes:
      - "./conf:/usr/local/etc/haproxy:ro"

  uniq1:
    image: golang:1.7
    networks:
      - my-net
    ports:
      - "11111:11111"
      - "11112:11112"
    volumes:
      - ".:/usr/local/go/src/github.com/bculberson/uniq:rw"
    command: bash -c "go run main.go -s --haddr uniq1:11111 --raddr uniq1:11112"
    working_dir: /usr/local/go/src/github.com/bculberson/uniq

  uniq2:
    image: golang:1.7
    networks:
      - my-net
    ports:
      - "11113:11113"
      - "11114:11114"
    volumes:
      - ".:/usr/local/go/src/github.com/bculberson/uniq:rw"
    command: bash -c "sleep 1 && go run main.go --join uniq1:11111 --haddr uniq2:11113 --raddr uniq2:11114"
    working_dir: /usr/local/go/src/github.com/bculberson/uniq

  uniq3:
    image: golang:1.7
    networks:
      - my-net
    ports:
      - "11115:11115"
      - "11116:11116"
    volumes:
      - ".:/usr/local/go/src/github.com/bculberson/uniq:rw"
    command: bash -c "sleep 1 && go run main.go --join uniq1:11111 --haddr uniq3:11115 --raddr uniq3:11116"
    working_dir: /usr/local/go/src/github.com/bculberson/uniq

networks:
  my-net:
    driver: bridge